<?php

namespace Eshop\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getFirstCategoryId(){
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('ca.id')
            ->from('ShopBundle:Category', 'ca')
            ->orderBy('ca.id', 'ASC')
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleResult()
            ;
    }
}
