<?php

namespace Eshop\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ManufacturerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManufacturerRepository extends EntityRepository
{
    public function getFirstManufacturerId(){
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('ma.id')
            ->from('ShopBundle:Manufacturer', 'ma')
            ->orderBy('ma.id', 'ASC')
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleResult()
            ;
    }
}
