<?php

namespace Eshop\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function getLastNews(){
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('n')
            ->from('ShopBundle:News', 'n')
            ->orderBy('n.date', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
