<?php

namespace App\Repository;

use App\Entity\Favourites;
use App\Entity\Product;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\Persistence\ManagerRegistry;
use Doctrine\ORM\NonUniqueResultException;
use App\Entity\User;
use Doctrine\ORM\NoResultException;

/**
 * FavouritesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavouritesRepository extends ServiceEntityRepository
{
    /**
     * Repository constructor.
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Favourites::class);
    }

    /**
     * @param User $user
     * @param integer $productId
     * @return bool
     * @throws NonUniqueResultException
     * @throws NoResultException
     */
    public function checkIsLiked(User $user, int $productId): bool
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('count(f.id)')
            ->from(Favourites::class, 'f')
            ->innerJoin('f.user', 'u')
            ->innerJoin('f.product', 'p')
            ->where('u = :user')
            ->andWhere('p.id = :product_id')
            ->setParameters([
                'product_id' => $productId,
                'user' => $user
            ]);

        if ($qb->getQuery()->getSingleScalarResult()) {
            return true;
        }

        return false;
    }

    /**
     * @param User $user
     * @param int[] $productIds
     * @return string[]
     */
    public function selectLikedProductIds(User $user, array $productIds): array
    {
        if (!count($productIds)) {
            return [];
        }

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('p.id')
            ->from(Favourites::class, 'f')
            ->innerJoin('f.user', 'u')
            ->innerJoin('f.product', 'p')
            ->andWhere('u = :user')
            ->andWhere($qb->expr()->In('p.id', ':product_ids'))
            ->setParameter('user', $user)
            ->setParameter('product_ids', $productIds);
        $result = $qb->getQuery()->getScalarResult();

        return array_map(function ($result) {
                return $result['id'] ?? null;
            },
            $result
        );
    }
}
