<?php

namespace App\Repository;

use App\Entity\Featured;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use Doctrine\ORM\NonUniqueResultException;

/**
 * FeaturedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturedRepository extends ServiceEntityRepository
{
    /**
     * Repository constructor.
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Featured::class);
    }

    /**
     * @return array|null
     * @throws NonUniqueResultException
     */
    public function getLatestProductOrder(): ?array
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('f.productOrder')
            ->from(Featured::class, 'f')
            ->addOrderBy('f.productOrder', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
