<?php

namespace Eshop\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;

/**
 * FeaturedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturedRepository extends EntityRepository
{
    /**
     * @return array|null
     * @throws NonUniqueResultException
     */
    public function getLatestProductOrder(): ?array
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('f.productOrder')
            ->from('ShopBundle:Featured', 'f')
            ->addOrderBy('f.productOrder', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
