<?php

namespace Eshop\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\QueryBuilder;
use Eshop\ShopBundle\Entity\Manufacturer;

/**
 * ManufacturerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManufacturerRepository extends EntityRepository
{
    /**
     * @param bool $showEmpty
     * @param string $order
     * @param string $sort
     * @return Manufacturer[]|null
     */
    public function getAllManufacturers(bool $showEmpty = true, string $sort = 'name', string $order = 'ASC'): array
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('c')
            ->from('ShopBundle:Manufacturer', 'c');

        if (!$showEmpty) {
            $qb->innerJoin('c.products', 'p')
                ->andWhere('p.quantity <> 0');
        }

        $qb->orderBy('c.' . $sort, $order);

        return $qb->getQuery()->getResult();
    }

    /**
     * query for admin paginator
     *
     * @return QueryBuilder
     */
    public function getAllManufacturersAdminQB(): QueryBuilder
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('m')
            ->from('ShopBundle:Manufacturer', 'm');

        return $qb;
    }

    /**
     * @param string $slug
     * @return Manufacturer|null
     * @throws NonUniqueResultException
     */
    public function findBySlug(string $slug): ?Manufacturer
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('m')
            ->from('ShopBundle:Manufacturer', 'm')
            ->where('m.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @return Manufacturer|null
     * @throws NonUniqueResultException
     */
    public function getFirstManufacturer(): ?Manufacturer
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('ma')
            ->from('ShopBundle:Manufacturer', 'ma')
            ->orderBy('ma.id', 'ASC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @return array
     */
    public function getArrayForSitemap(): array
    {
        return $this->createQueryBuilder('m')
            ->select('m.slug, m.dateUpdated')
            ->getQuery()
            ->getArrayResult();
    }
}
