<?php

namespace Eshop\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ManufacturerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManufacturerRepository extends EntityRepository
{
    public function findBySlug($slug){
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('m')
            ->from('ShopBundle:Manufacturer', 'm')
            ->where('m.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getSingleResult();
    }

    public function getFirstManufacturer(){
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('ma')
            ->from('ShopBundle:Manufacturer', 'ma')
            ->orderBy('ma.id', 'ASC')
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleResult()
            ;
    }
}
