<?php

namespace Eshop\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\QueryBuilder;
use Eshop\ShopBundle\Entity\News;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    /**
     * @param $slug string
     * @return mixed
     * @throws NoResultException
     * @throws NonUniqueResultException
     */
    public function findBySlug(string $slug): ?News
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('n')
            ->from('ShopBundle:News', 'n')
            ->where('n.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getSingleResult();
    }

    /**
     * query for admin paginator
     *
     * @return QueryBuilder
     */
    public function getAllNewsAdminQB(): QueryBuilder
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('n')
            ->from('ShopBundle:News', 'n');

        return $qb;
    }

    /**
     * @return News|null
     * @throws NonUniqueResultException
     */
    public function getLastNews(): ?News
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('n')
            ->from('ShopBundle:News', 'n')
            ->orderBy('n.date', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * Create query for paginator
     *
     * @return QueryBuilder
     */
    public function getNewsQB(): QueryBuilder
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('a')
            ->from('ShopBundle:News', 'a')
            ->orderBy('a.date', 'DESC');
    }
}
