<?php

namespace Eshop\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Eshop\UserBundle\Entity\User;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends EntityRepository
{
    /**
     * query for admin paginator
     *
     * @return QueryBuilder
     */
    public function getAllOrdersAdminQB(): QueryBuilder
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select(['o', 'u'])
            ->from('ShopBundle:Orders', 'o')
            ->leftJoin('o.user', 'u')
            ->addOrderBy('o.date', 'DESC');

        return $qb;
    }

    /**
     * return query to get users orders
     *
     * @param User $user
     * @return QueryBuilder
     */
    public function getUserOrdersAdminQB(User $user): QueryBuilder
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('o')
            ->from('ShopBundle:Orders', 'o')
            ->innerJoin('o.user', 'ou')
            ->where('ou = :user')
            ->addOrderBy('o.date', 'DESC')
            ->setParameter('user', $user);

        return $qb;
    }
}
