<?php

namespace Eshop\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Eshop\ShopBundle\Entity\StaticPage;

/**
 * StaticPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaticPageRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getHeaders(): array
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('a.title, a.slug')
            ->from('ShopBundle:StaticPage', 'a')
            ->where('a.enabled = 1')
            ->addOrderBy('a.orderNum', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $slug
     * @return StaticPage|null
     * @throws NonUniqueResultException
     */
    public function findBySlug(string $slug): ?StaticPage
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('a')
            ->from('ShopBundle:StaticPage', 'a')
            ->where('a.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @return array
     */
    public function getArrayForSitemap(): array
    {
        return $this->createQueryBuilder('sp')
            ->select('sp.slug')
            ->getQuery()
            ->getArrayResult();
    }
}
