<?php

namespace Eshop\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StaticPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaticPageRepository extends EntityRepository
{
    public function getHeaders(){
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('a.title, a.slug')
            ->from('ShopBundle:StaticPage', 'a')
            ->where('a.enabled = 1')
            ->addOrderBy('a.orderNum', 'ASC')
            ->getQuery()
            ->getResult();
    }

    public function findBySlug($slug){
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('a')
            ->from('ShopBundle:StaticPage', 'a')
            ->where('a.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
